2015-01-24 16:13:01 Error: Fatal Error (1): Call to a member function find() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\InvestmentsController.php, line 59]
2015-01-24 16:13:01 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /zespolowe/investments/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 16:54:43 Error: Fatal Error (1): Call to a member function find() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\InvestmentsController.php, line 59]
2015-01-24 16:54:43 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /zespolowe/investments/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 16:57:41 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /zespolowe/users/login
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-01-24 16:59:53 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 25]
2015-01-24 16:59:53 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/users/login
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 25)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 25, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 25, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:02:22 Error: [MissingActionException] Action UsersController::index() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'index',
)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-01-24 17:03:45 Error: Fatal Error (1): Call to a member function find() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\InvestmentsController.php, line 59]
2015-01-24 17:03:45 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /zespolowe/investments/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 59, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:27:59 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2015-01-24 17:31:13 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-24 17:31:13 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:32:57 Error: Fatal Error (4): syntax error, unexpected '}', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 38]
2015-01-24 17:32:57 Error: [FatalErrorException] syntax error, unexpected '}', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:33:36 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 38]
2015-01-24 17:33:36 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 38, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:37:33 Error: Fatal Error (1): Call to a member function setFlash() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 32]
2015-01-24 17:37:33 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 32, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 32, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:49:28 Error: Fatal Error (1): Class 'BlowfishPasswordHasher' not found in [E:\XAMPP\htdocs\zespolowe\app\Model\User.php, line 20]
2015-01-24 17:49:28 Error: [FatalErrorException] Class 'BlowfishPasswordHasher' not found
Request URL: /zespolowe/users/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'Blowfish...', 'E:\\XAMPP\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Blowfish...', 'E:\\XAMPP\\htdocs...', 20, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'Blowfish...', 'E:\\XAMPP\\htdocs...', 20, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:50:41 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-24 17:50:41 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 17:50:43 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-24 17:50:43 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:11:08 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 34]
2015-01-24 18:11:08 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 34, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 34, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:11:38 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 48]
2015-01-24 18:11:38 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 48, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 48, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:29:46 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /zespolowe/login
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:29:49 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-24 18:29:49 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:37:05 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /zespolowe/login
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:37:19 Error: [MissingControllerException] Controller class LoginController could not be found.
Exception Attributes: array (
  'class' => 'LoginController',
  'plugin' => NULL,
)
Request URL: /zespolowe/login
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:45:02 Error: Fatal Error (1): Class 'SimplePasswordHasher' not found in [E:\XAMPP\htdocs\zespolowe\app\Model\User.php, line 20]
2015-01-24 18:45:02 Error: [FatalErrorException] Class 'SimplePasswordHasher' not found
Request URL: /zespolowe/users/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'SimplePa...', 'E:\\XAMPP\\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'SimplePa...', 'E:\\XAMPP\\htdocs...', 20, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'SimplePa...', 'E:\\XAMPP\\htdocs...', 20, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:46:25 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-24 18:46:25 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:52:43 Error: Fatal Error (4): syntax error, unexpected '}', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 47]
2015-01-24 18:52:43 Error: [FatalErrorException] syntax error, unexpected '}', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:53:17 Error: Fatal Error (4): syntax error, unexpected '}', expecting variable (T_VARIABLE) in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 47]
2015-01-24 18:53:17 Error: [FatalErrorException] syntax error, unexpected '}', expecting variable (T_VARIABLE)
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 18:53:36 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:54:02 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:54:15 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:54:18 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:55:14 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:55:23 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:55:29 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:56:00 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:56:06 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:57:50 Error: [MissingControllerException] Controller class IndexController could not be found.
Exception Attributes: array (
  'class' => 'IndexController',
  'plugin' => NULL,
)
Request URL: /zespolowe/index
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-24 18:58:47 Error: [NotFoundException] Invalid user
Request URL: /zespolowe/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-01-24 19:00:28 Error: Fatal Error (4): syntax error, unexpected ''Auth'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 37]
2015-01-24 19:00:28 Error: [FatalErrorException] syntax error, unexpected ''Auth'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/users/view
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 37)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 37, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 37, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:01:01 Error: [NotFoundException] Invalid user
Request URL: /zespolowe/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-01-24 19:01:32 Error: [NotFoundException] Invalid user
Request URL: /zespolowe/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-01-24 19:01:33 Error: [NotFoundException] Invalid user
Request URL: /zespolowe/users/view
Stack Trace:
#0 [internal function]: UsersController->view()
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-01-24 19:14:06 Error: Fatal Error (4): syntax error, unexpected '=', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 45]
2015-01-24 19:14:06 Error: [FatalErrorException] syntax error, unexpected '=', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:14:19 Error: Fatal Error (4): syntax error, unexpected '=', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 45]
2015-01-24 19:14:19 Error: [FatalErrorException] syntax error, unexpected '=', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 45, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:14:32 Error: Fatal Error (4): syntax error, unexpected end of file in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 70]
2015-01-24 19:14:32 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:14:44 Error: Fatal Error (4): syntax error, unexpected end of file in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 70]
2015-01-24 19:14:44 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:14:45 Error: Fatal Error (4): syntax error, unexpected end of file in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 70]
2015-01-24 19:14:45 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-24 19:14:45 Error: Fatal Error (4): syntax error, unexpected end of file in [E:\XAMPP\htdocs\zespolowe\app\View\Layouts\default.ctp, line 70]
2015-01-24 19:14:45 Error: [FatalErrorException] syntax error, unexpected end of file
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 70, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 10:43:35 Error: [MissingConnectionException] Database connection "Mysql" is missing, or could not be created.
Exception Attributes: array (
  'class' => 'Mysql',
  'message' => 'SQLSTATE[HY000] [1045] Access denied for user \'root\'@\'localhost\' (using password: NO)',
  'enabled' => true,
)
Request URL: /zespolowe2/zespolowe/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(260): Mysql->connect()
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\ConnectionManager.php(105): DboSource->__construct(Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(3524): ConnectionManager::getDataSource('default')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1136): Model->setDataSource('default')
#4 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(3551): Model->setSource('users')
#5 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1369): Model->getDataSource()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\View\Helper\FormHelper.php(215): Model->schema()
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\View\Helper\FormHelper.php(468): FormHelper->_introspectModel('User', 'fields')
#8 C:\wamp\www\zespolowe2\zespolowe\app\View\Users\login.ctp(5): FormHelper->create('User')
#9 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\View\View.php(948): include('C:\wamp\www\zes...')
#10 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\View\View.php(910): View->_evaluate('C:\wamp\www\zes...', Array)
#11 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\View\View.php(471): View->_render('C:\wamp\www\zes...')
#12 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#13 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#14 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#15 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2015-01-26 11:25:53 Error: [MissingControllerException] Controller class InvestmentController could not be found.
Exception Attributes: array (
  'class' => 'InvestmentController',
  'plugin' => NULL,
)
Request URL: /zespolowe2/zespolowe/investment/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-26 11:41:44 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'last_login' doesn't have a default value
Request URL: /zespolowe2/zespolowe/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(User), Array, Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\UsersController.php(78): Model->save(Array)
#5 [internal function]: UsersController->add()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 11:50:34 Error: [MissingControllerException] Controller class TimetableController could not be found.
Exception Attributes: array (
  'class' => 'TimetableController',
  'plugin' => NULL,
)
Request URL: /zespolowe2/zespolowe/timetable/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-26 11:50:47 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe2/zespolowe/timetables/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 11:53:37 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 11:53:37 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 11:53:45 Error: [NotFoundException] Invalid timetable
Request URL: /zespolowe2/zespolowe/timetables/delete/
Stack Trace:
#0 [internal function]: TimetablesController->delete()
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#4 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2015-01-26 11:53:55 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe2/zespolowe/timetables/index/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 11:54:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 11:54:00 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 11:56:34 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe2/zespolowe/timetables/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 11:56:37 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe2/zespolowe/timetables/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 11:58:02 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 11:58:02 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 11:58:40 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 11:58:40 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 11:58:42 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 11:58:42 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:00:19 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 12:00:19 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:00:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 12:00:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:02:00 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 12:02:00 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /zespolowe2/zespolowe/timetables/add
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\wamp\www\zes...', 58, Array)
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
<<<<<<< HEAD
2015-01-26 12:15:01 Error: Fatal Error (4): syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 42]
2015-01-26 12:15:01 Error: [FatalErrorException] syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:15:37 Error: Fatal Error (4): syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 42]
2015-01-26 12:15:37 Error: [FatalErrorException] syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:15:40 Error: Fatal Error (4): syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 42]
2015-01-26 12:15:40 Error: [FatalErrorException] syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:15:53 Error: Fatal Error (4): syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 42]
2015-01-26 12:15:53 Error: [FatalErrorException] syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:15:55 Error: Fatal Error (4): syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 42]
2015-01-26 12:15:55 Error: [FatalErrorException] syntax error, unexpected ''authenticate'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 42, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:17:48 Error: Fatal Error (4): syntax error, unexpected ')', expecting variable (T_VARIABLE) in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 49]
2015-01-26 12:17:48 Error: [FatalErrorException] syntax error, unexpected ')', expecting variable (T_VARIABLE)
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:25:11 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 47]
2015-01-26 12:25:11 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:25:32 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 47]
2015-01-26 12:25:32 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:25:56 Error: Fatal Error (4): syntax error, unexpected '}', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 49]
2015-01-26 12:25:56 Error: [FatalErrorException] syntax error, unexpected '}', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 49, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:26:22 Error: Fatal Error (4): syntax error, unexpected ';', expecting ')' in [E:\XAMPP\htdocs\zespolowe\app\Controller\AppController.php, line 47]
2015-01-26 12:26:22 Error: [FatalErrorException] syntax error, unexpected ';', expecting ')'
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 47, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:34:18 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-26 12:34:18 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:38:51 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-26 12:38:51 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:40:08 Error: Fatal Error (1): Call to a member function loggedIn() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 18]
2015-01-26 12:40:08 Error: [FatalErrorException] Call to a member function loggedIn() on null
Request URL: /zespolowe/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 18, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:54:03 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe/timetables/
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 12:54:09 Error: Fatal Error (1): Call to a member function find() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 12:54:09 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 12:59:42 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 13:00:19 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 13:02:20 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 13:02:41 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 13:03:41 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 13:03:46 Error: [MissingControllerException] Controller class TimetablewsController could not be found.
Exception Attributes: array (
  'class' => 'TimetablewsController',
  'plugin' => NULL,
)
Request URL: /zespolowe/timetablews
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2015-01-26 13:03:49 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe/timetables
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 13:04:00 Error: Fatal Error (1): Call to a member function find() on null in [E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php, line 58]
2015-01-26 13:04:00 Error: [FatalErrorException] Call to a member function find() on null
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'E:\\XAMPP\\htdocs...', 58, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 14:28:41 Error: Fatal Error (4): syntax error, unexpected '}' in [E:\XAMPP\htdocs\zespolowe\app\Controller\UsersController.php, line 29]
2015-01-26 14:28:41 Error: [FatalErrorException] syntax error, unexpected '}'
Request URL: /zespolowe/users/logout
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 29)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 29, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 29, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 14:30:39 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:34:28 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:35:08 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:35:15 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`timetables`, CONSTRAINT `fk_users_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/timetables/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:35:24 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Timetable.users_id' in 'on clause'
Request URL: /zespolowe/timetables
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Timetab...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Timetab...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Timetab...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Timetable), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\TimetablesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TimetablesController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 14:39:51 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Advance.users_id' in 'on clause'
Request URL: /zespolowe/advances
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Advance...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Advance...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Advance...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Advance), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\AdvancesController.php(25): PaginatorComponent->paginate()
#8 [internal function]: AdvancesController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(AdvancesController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdvancesController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 14:40:48 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`advances`, CONSTRAINT `fk_advances` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/advances/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Advance), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\AdvancesController.php(51): Model->save(Array)
#5 [internal function]: AdvancesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(AdvancesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdvancesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:41:28 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`advances`, CONSTRAINT `fk_advances` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/advances/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Advance), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\AdvancesController.php(51): Model->save(Array)
#5 [internal function]: AdvancesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(AdvancesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdvancesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 14:41:32 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`advances`, CONSTRAINT `fk_advances` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/advances/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Advance), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\AdvancesController.php(51): Model->save(Array)
#5 [internal function]: AdvancesController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(AdvancesController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AdvancesController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 15:54:33 Error: Fatal Error (4): syntax error, unexpected '<' in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 13]
2015-01-26 15:54:33 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 13)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 13, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 13, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:55:16 Error: Fatal Error (4): syntax error, unexpected 'endif' (T_ENDIF) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 30]
2015-01-26 15:55:16 Error: [FatalErrorException] syntax error, unexpected 'endif' (T_ENDIF)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:55:42 Error: Fatal Error (4): syntax error, unexpected 'endif' (T_ENDIF) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 30]
2015-01-26 15:55:42 Error: [FatalErrorException] syntax error, unexpected 'endif' (T_ENDIF)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:56:14 Error: Fatal Error (4): syntax error, unexpected 'endif' (T_ENDIF) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 26]
2015-01-26 15:56:14 Error: [FatalErrorException] syntax error, unexpected 'endif' (T_ENDIF)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 26)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 26, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 26, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:57:10 Error: Fatal Error (4): syntax error, unexpected 'endif' (T_ENDIF) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 30]
2015-01-26 15:57:10 Error: [FatalErrorException] syntax error, unexpected 'endif' (T_ENDIF)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 30, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:57:31 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 24]
2015-01-26 15:57:31 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:58:36 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 24]
2015-01-26 15:58:36 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:59:02 Error: Fatal Error (4): syntax error, unexpected '||' (T_BOOLEAN_OR) in [E:\XAMPP\htdocs\zespolowe\app\View\Elements\mainmenu.ctp, line 24]
2015-01-26 15:59:02 Error: [FatalErrorException] syntax error, unexpected '||' (T_BOOLEAN_OR)
Request URL: /zespolowe/users
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'E:\\XAMPP\\htdocs...', 24, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2015-01-26 15:59:58 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Transaction.users_id' in 'on clause'
Request URL: /zespolowe/transactions
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Transac...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Transac...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Transac...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Transaction), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\TransactionsController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TransactionsController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TransactionsController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TransactionsController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 16:00:23 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Transaction.timetables_id' in 'on clause'
Request URL: /zespolowe/transactions
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Transac...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Transac...', Array, Array)
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1106): DboSource->fetchAll('SELECT `Transac...', false)
#4 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2947): DboSource->read(Object(Transaction), Array)
#5 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(2919): Model->_readDataSource('all', Array)
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Component\PaginatorComponent.php(196): Model->find('all', Array)
#7 E:\XAMPP\htdocs\zespolowe\app\Controller\TransactionsController.php(25): PaginatorComponent->paginate()
#8 [internal function]: TransactionsController->index()
#9 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TransactionsController), Array)
#10 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#11 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TransactionsController), Object(CakeRequest))
#12 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2015-01-26 16:01:31 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`transactions`, CONSTRAINT `fk_users_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/transactions/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Transaction), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TransactionsController.php(51): Model->save(Array)
#5 [internal function]: TransactionsController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TransactionsController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TransactionsController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 16:02:14 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`zespolowe`.`transactions`, CONSTRAINT `fk_users_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe/transactions/add
Stack Trace:
#0 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 E:\XAMPP\htdocs\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Transaction), Array, Array)
#4 E:\XAMPP\htdocs\zespolowe\app\Controller\TransactionsController.php(51): Model->save(Array)
#5 [internal function]: TransactionsController->add()
#6 E:\XAMPP\htdocs\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TransactionsController), Array)
#7 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 E:\XAMPP\htdocs\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TransactionsController), Object(CakeRequest))
#9 E:\XAMPP\htdocs\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
=======
2015-01-26 12:07:25 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'last_login' doesn't have a default value
Request URL: /zespolowe2/zespolowe/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(User), Array, Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\UsersController.php(78): Model->save(Array)
#5 [internal function]: UsersController->add()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 12:16:41 Error: [PDOException] SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'pesel' at row 1
Request URL: /zespolowe2/zespolowe/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(User), Array, Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\UsersController.php(78): Model->save(Array)
#5 [internal function]: UsersController->add()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 12:20:24 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value
Request URL: /zespolowe2/zespolowe/timetables/add/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 12:22:29 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value
Request URL: /zespolowe2/zespolowe/timetables/add/
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `ze...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(1012): DboSource->execute('INSERT INTO `ze...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(1854): DboSource->create(Object(Timetable), Array, Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\TimetablesController.php(51): Model->save(Array)
#5 [internal function]: TimetablesController->add()
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(TimetablesController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(TimetablesController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2015-01-26 12:38:26 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`zespolowe`.`investments`, CONSTRAINT `fk_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
Request URL: /zespolowe2/zespolowe/users/delete/2
Stack Trace:
#0 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('DELETE `User` F...', Array)
#2 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Datasource\Database\Mysql.php(454): DboSource->execute('DELETE `User` F...')
#3 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Model\Model.php(2634): Mysql->delete(Object(User), Array)
#4 C:\wamp\www\zespolowe2\zespolowe\app\Controller\UsersController.php(124): Model->delete()
#5 [internal function]: UsersController->delete('2')
#6 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#7 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#8 C:\wamp\www\zespolowe2\zespolowe\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#9 C:\wamp\www\zespolowe2\zespolowe\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
>>>>>>> 0f1b48f33ea5443228732afcfca179b6c11517cc
#10 {main}
